blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/pdfme/pdfme/discussions
    about: I have questions about pdfme. Please ask and answer questions at https://github.com/pdfme/pdfme/discussions
